### ISSUE TITLE
.command命令添加MCDR指令支持

### ISSUE THREAD

**Issue by LBY123165** [Minecraft-QQBot/Plugin.McdReforged#1]
可以尝试检测MCDR的log（？

**Comment by LBY123165** [comment]
可以尝试调用MCDR官方的文本交互接口（？
https://docs.mcdreforged.com/zh-cn/latest/code_references/ServerInterface.html#text-interaction

**Comment by Lonely-Sails** [comment]
> 可以尝试调用MCDR官方的文本交互接口（？ https://docs.mcdreforged.com/zh-cn/latest/code_references/ServerInterface.html#text-interaction

这个一样没有返回值

**Comment by Lonely-Sails** [comment]
目前为止没有发现任何方法可以获取 Mcdr 命令执行后的输出。
